[project]
name = "swe-codegen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "codegen>=0.17.2",
    "datasets>=3.3.0",
    "dump>=0.0.5",
    "rich-click>=1.8.5",
]
